services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:SUA_CHAVE_AQUI
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://nomedoseuservico.onrender.com
