<?php

// config/auth_permissions.php
return [
    // Senha para registro administrativo
    'admin_registration_password' => env('ADMIN_REGISTRATION_PASSWORD', 'admin2024!'),
    
    // Configurações de permissões por role
    'role_permissions' => [
        'admin' => [
            'view_dashboard',
            'view_reports',
            'export_reports',
            'manage_users',
            'create_users',
            'edit_users',
            'delete_users',
            'activate_users',
            'manage_products',
            'create_products',
            'edit_products',
            'delete_products',
            'adjust_stock',
            'manage_categories',
            'create_categories',
            'edit_categories',
            'delete_categories',
            'view_sales',
            'create_sales',
            'edit_sales',
            'delete_sales',
            'manage_orders',
            'create_orders',
            'edit_orders',
            'delete_orders',
            'convert_orders',
            'manage_debts',
            'create_debts',
            'edit_debts',
            'delete_debts',
            'cancel_debts',
            'manage_payments',
            'manage_expenses',
            'create_expenses',
            'edit_expenses',
            'delete_expenses',
            'manage_stock',
            'view_stock_movements',
            'create_stock_movements',
            'manage_settings',
            'backup_system',
            'view_logs',
        ],
        
        'manager' => [
            'view_dashboard',
            'view_reports',
            'export_reports',
            'view_products',
            'create_products',
            'edit_products',
            'adjust_stock',
            'view_categories',
            'view_sales',
            'create_sales',
            'edit_sales',
            'view_orders',
            'create_orders',
            'edit_orders',
            'convert_orders',
            'view_debts',
            'create_debts',
            'edit_debts',
            'manage_payments',
            'view_expenses',
            'create_expenses',
            'edit_expenses',
            'manage_stock',
            'view_stock_movements',
            'create_stock_movements',
        ],
        
        'staff' => [
            'view_dashboard',
            'view_products',
            'edit_products',
            'adjust_stock',
            'view_sales',
            'create_sales',
            'edit_own_sales',
            'view_orders',
            'create_orders',
            'edit_own_orders',
            'view_debts',
            'create_debts',
            'manage_payments',
            'view_expenses',
            'create_expenses',
            'view_stock_movements',
            'view_basic_reports',
        ],
    ],
    
    // Menu items configuration
    'menu_items' => [
        'dashboard' => ['icon' => 'fa-tachometer-alt', 'permission' => null],
        'pos' => ['icon' => 'fa-cash-register', 'permission' => null],
        'products' => ['icon' => 'fa-box', 'permission' => null],
        'categories' => ['icon' => 'fa-tags', 'permission' => 'manage_categories', 'admin_only' => true],
        'orders' => ['icon' => 'fa-clipboard-list', 'permission' => null],
        'sales' => ['icon' => 'fa-shopping-cart', 'permission' => null],
        'debts' => ['icon' => 'fa-credit-card', 'permission' => null],
        'expenses' => ['icon' => 'fa-receipt', 'permission' => null],
        'stock' => ['icon' => 'fa-exchange-alt', 'permission' => null],
        'reports' => ['icon' => 'fa-chart-bar', 'permission' => null],
        'users' => ['icon' => 'fa-users', 'permission' => 'manage_users', 'admin_only' => true],
        'profile' => ['icon' => 'fa-user-cog', 'permission' => null],
        'settings' => ['icon' => 'fa-cog', 'permission' => 'manage_settings', 'admin_only' => true],
    ]
];


